---
# host group must be specified at command line, e.g.
# ansible-playbook configure.yml -e hosts=ec2hosts
- name: configuration
  hosts: "{{ hosts }}"
  user: ubuntu
  gather_facts: true
  roles:
    - { role: packages }
    - { role: set_timezone }
    - { role: system_setup }
    - { role: capistrano_setup }
    - { role: ruby }
    - { role: openjdk1_8 }
    - { role: hydra-stack/install }
    - { role: hydra-stack/config-capistrano }
    # if using imagemagick and/or ffmpeg, uncomment:
    # - { role: ffmpeg }
    # - { role: imagemagick }
    - { role: sufia_dependencies/install }
    - { role: sufia_dependencies/config }
    # if using RIIIF, uncomment this role
    # - { role: RIIIF }
    - { role: webserver/install }
    - { role: webserver/config }
    - { role: app-config }
    - { role: deploy }
