---
# ROLE: launch_ec2
# roles/launch_ec2/tasks/main.yml
#
# Launches a new ec2 instance and attaches dedicated data volume

- name: provision an ec2 instance
  ec2:
    key_name: "{{ ec2_key }}" 
    region: "{{ ec2_region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    # assign_public_ip: yes
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: true
    count: 1
    state: present
    count_tag:
      Name: "{{ aws_tag }}"
    instance_tags: 
      Name: "{{ aws_tag }}"
    volumes:
          - device_name: /dev/sdf
            volume_size: 40
            delete_on_termination: true
  register: ec2

- name: associate EIP with instance
  ec2_eip:
    in_vpc: yes
    reuse_existing_ip_allowed: yes
    state: present
    instance_id: "{{ ec2.instance_ids[0] }}"
  register: instance_eip

- debug: var=instance_eip.public_ip

- name: Add all instance public IPs to in-memory host group
  add_host: hostname={{ instance_eip.public_ip }} groups=newboxes
  with_items: ec2.instances

- name: Add all instance public IPs to on-disc host group
  lineinfile: dest=hosts line={{ instance_eip.public_ip }} insertafter=ec2hosts
  with_items: ec2.instances

- name: give ssh time to come up
#  wait_for: host={{ item.public_ip }} port=22 state=started
  wait_for: host={{ instance_eip.public_ip }} port=22 state=started
  with_items: ec2.instances

- name: pause another few seconds for other services to start
  pause: seconds=5
