---
# ROLE: packages
# roles/packages/tasks/main.yml
#
# updates apt, installs packages used by other installation/configuration tasks
#
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: update apt cache
  become: yes
  package: update_cache=yes

- name: install aptitude
  # on Debian Jessie aptitude is not installed by default, without it apt-get upgrade fails
  become: yes
  package: name=aptitude state=installed

- name: upgrade apt packages
  become: yes
  package: upgrade=full

- name: install dev tools and libraries
  become: yes
  package: name={{ item }} state=latest
  with_items: "{{ dev_tools_and_libs }}"
