---
  # solr 5 requires java 8
  # until java 8 becomes the default package
  # you must include the openjdk1_8 role before the hydra-stack role when installing solr 5.x

- name: download solr tarball
  become: yes
  get_url: url=http://archive.apache.org/dist/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/solr-{{ solr_version }}.tgz force=no
  # when we upgrade to ansible 2.0, add checksum="md5:{{ solr_md5 }}" 

- name: untar solr tarball
  become: yes
  unarchive: src={{ install_path }}/solr-{{ solr_version }}.tgz dest={{ install_path }}/ creates={{ install_path }}/solr-{{ solr_version }}/bin/solr copy=no

- name: check if solr 5 is installed
  stat: path=/etc/default/solr.in.sh
  register: solr_5_script

- name: run solr 5 service script
  when: solr_5_script.stat.exists == False
  become: yes
  shell: bash {{ install_path }}/solr-{{ solr_version }}/bin/install_solr_service.sh {{ install_path }}/solr-{{ solr_version }}.tgz

- name: create default collection
  become: yes
  become_user: solr
  shell: /opt/solr/bin/solr create -c {{ solr_core }} -d basic_configs creates=/var/solr/data/{{ solr_core }}

- name: symlink schema from code to solr
  become: yes
  file: src={{ app_root }}/solr/config/schema.xml dest=/var/solr/data/{{ solr_core }}/conf/schema.xml state=link force=yes

- name: symlink solrconfig from code to solr
  become: yes
  file: src={{ app_root }}/solr/config/solrconfig.xml dest=/var/solr/data/{{ solr_core }}/conf/solrconfig.xml state=link force=yes

- name: set the solr port
  set_fact:
    solr_port: 8983
